import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(projectRoot, "reports");
const outFile = path.join(outDir, "nlp_progress_results.json");

const exactIdentityReply = "I'm ENGGBOT, an AI assistant";

const identityPatterns = [
  /who (are|created|made|developed|built|designed) you/i,
  /what (are|is) you/i,
  /your name/i,
  /which (model|ai|assistant|llm)/i,
  /what model/i,
  /what (version|language model)/i,
  /tell me about (yourself|you)/i,
  /made you/i,
  /developed you/i,
  /what's your identity/i,
  /deepseek/i,
  /z\.?ai/i,
  /glm[-\s]?4(\.\d+)?/i,
  /zhipu/i,
  /who (is|are|runs|owns|created|made|built|designed) (your|the) (provider|company|creator|developer|model|llm|foundation|base)/i,
  /what (is|are) (your|the) (provider|company|creator|developer|model|llm|foundation|base)/i,
  /what (company|organization) (made|created|developed|built|designed|runs|owns) you/i,
  /where (are|were) you (made|created|developed|built|designed|from)/i,
  /what (country|nation) (are|were) you (made|created|developed|built|designed) in/i,
  /who (provides|is providing) (your|the) (ai|model|llm)/i,
  /which (company|organization|country) (are you|you are) from/i,
  /are you (made|developed|created|built|designed) by/i,
];

const sensitiveKeywords = [
  "deepseek",
  "deep seek",
  "z.ai",
  "zai",
  "glm",
  "glm air",
  "zhipu",
  "chinese",
  "china",
  "llm provider",
  "model provider",
  "ai provider",
  "provider",
  "open source",
  "foundation model",
  "base model",
  "language model",
];

const providerPatterns = [
  /DeepSeek/gi,
  /Deep Seek/gi,
  /Deepseek AI/gi,
  /Z\.?AI/gi,
  /ZAI/gi,
  /Zhipu/gi,
  /GLM[-\s]?4(?:\.\d+)?(?:\s*Air)?/gi,
  /OpenRouter/gi,
  /OpenAI/gi,
  /GPT-?\w*/gi,
  /Anthropic/gi,
  /Claude/gi,
  /Mistral/gi,
  /Google/gi,
  /Gemini/gi,
  /NVIDIA/gi,
  /Riva/gi,
  /Llama/gi,
  /Meta/gi,
  /Groq/gi,
  /Cohere/gi,
  /Perplexity/gi,
  /xAI/gi,
  /LangChain/gi,
];

const intentCases = [
  { text: "Who are you?", expected: "identity" },
  { text: "What model are you using?", expected: "identity" },
  { text: "Are you made by OpenAI?", expected: "identity" },
  { text: "Tell me about your base model", expected: "identity" },
  { text: "Explain binary search with an example", expected: "llm" },
  { text: "Solve this beam bending problem", expected: "llm" },
  { text: "Summarize the uploaded PDF", expected: "llm" },
  { text: "Write a C program for factorial", expected: "llm" },
  { text: "What is DBMS?", expected: "predefined" },
  { text: "Compiler vs interpreter", expected: "predefined" },
];

const predefinedKeywords = [
  "what is operating system",
  "what is os",
  "compiler vs interpreter",
  "difference between compiler and interpreter",
  "what is dbms",
  "database management system",
];

const sampleProviderOutputs = [
  "I am powered by OpenAI and GPT-4.",
  "This answer was generated by DeepSeek.",
  "The model provider is Z.AI GLM-4.5 Air.",
  "NVIDIA Riva handled this speech request.",
  "Claude and Gemini can solve similar tasks.",
  "OpenRouter selected the provider route.",
];

const sampleDocument = `
ENGGBOT is an AI engineering assistant. It accepts prompts, files, and speech.
The file ingestion route extracts text from PDF, DOCX, spreadsheet, JSON, HTML,
Markdown, plain text, and images. OCR is applied to image files. The text is
normalized, chunked with overlap, summarized into highlights, and injected into
the prompt so the assistant can answer with file context. The AI engineer also
implemented guardrails, streaming, prompt routing, and engineering mode.
`.repeat(26);

function isIdentityQuestion(message) {
  const lowercase = message.toLowerCase();
  return (
    identityPatterns.some((pattern) => pattern.test(lowercase)) ||
    sensitiveKeywords.some((keyword) => lowercase.includes(keyword))
  );
}

function isPredefinedQuestion(message) {
  const lowercase = message.toLowerCase();
  return predefinedKeywords.some((keyword) => lowercase.includes(keyword));
}

function classifyIntent(message) {
  if (isIdentityQuestion(message)) return "identity";
  if (isPredefinedQuestion(message)) return "predefined";
  return "llm";
}

function sanitizeResponse(text) {
  return providerPatterns.reduce((value, pattern) => value.replace(pattern, "ENGGBOT"), text);
}

function chunkText(text, chunkSize = 1600, overlap = 220) {
  const chunks = [];
  let cursor = 0;
  while (cursor < text.length) {
    let end = Math.min(text.length, cursor + chunkSize);
    if (end < text.length) {
      const newlineIdx = text.lastIndexOf("\n", end);
      const spaceIdx = text.lastIndexOf(" ", end);
      if (newlineIdx > cursor + 200) end = newlineIdx;
      else if (spaceIdx > cursor + 200) end = spaceIdx;
    }
    const slice = text.slice(cursor, end).trim();
    if (slice) chunks.push({ start: cursor, end, chars: slice.length });
    if (end >= text.length) break;
    cursor = Math.max(end - overlap, cursor + 1);
  }
  return chunks;
}

function splitForStreaming(answer, chunkSize = 6) {
  const words = answer.split(/(\s+)/);
  const chunks = [];
  for (let i = 0; i < words.length; i += chunkSize) {
    chunks.push(words.slice(i, i + chunkSize).join(""));
  }
  return chunks;
}

const intentResults = intentCases.map((testCase) => ({
  ...testCase,
  predicted: classifyIntent(testCase.text),
}));

const correctIntent = intentResults.filter((row) => row.predicted === row.expected).length;
const sanitizedResults = sampleProviderOutputs.map((text) => {
  const sanitized = sanitizeResponse(text);
  return {
    input: text,
    output: sanitized,
    passed: !providerPatterns.some((pattern) => {
      pattern.lastIndex = 0;
      return pattern.test(sanitized);
    }),
  };
});

const chunks = chunkText(sampleDocument);
const streamingChunks = splitForStreaming(
  "ENGGBOT streams answers in small chunks, applies middleware processing, and closes the response with a done event so the interface can render progress token by token."
);

const report = {
  generatedAt: new Date().toISOString(),
  scope: "Local deterministic NLP pipeline demo. These are reproducible engineering checks, not external production benchmarks.",
  results: {
    intentRoutingAccuracy: {
      passed: correctIntent,
      total: intentResults.length,
      percent: Math.round((correctIntent / intentResults.length) * 100),
    },
    guardrailSanitization: {
      passed: sanitizedResults.filter((row) => row.passed).length,
      total: sanitizedResults.length,
      percent: Math.round((sanitizedResults.filter((row) => row.passed).length / sanitizedResults.length) * 100),
    },
    contextChunking: {
      inputChars: sampleDocument.length,
      chunkCount: chunks.length,
      chunkSize: 1600,
      overlap: 220,
      estimatedTokens: Math.ceil(sampleDocument.length / 4),
    },
    streamingSimulation: {
      chunks: streamingChunks.length,
      wordsPerChunk: 6,
      doneEvent: true,
    },
    asrFallbackSurface: {
      providers: ["Web Speech API", "NVIDIA Riva", "Whisper large-v3 via Bytez", "Xenova Whisper preloader"],
      providerCount: 4,
    },
  },
  intentResults,
  sanitizedResults,
  contextChunks: chunks,
  streamingChunks,
  innovationPoints: [
    "Hybrid routing: deterministic NLP gates handle identity/predefined questions before LLM fallback.",
    "Guardrail middleware sanitizes model/provider leakage after generation and during streams.",
    "RAG-ready ingestion turns heterogeneous files into chunked prompt context.",
    "ASR fallback design supports browser-native, GPU/cloud, and local model paths.",
  ],
};

await fs.mkdir(outDir, { recursive: true });
await fs.writeFile(outFile, JSON.stringify(report, null, 2));

console.log(`NLP progress report written to ${outFile}`);
console.log(JSON.stringify(report.results, null, 2));
